name: Playwright Tests

on:
  pull_request:
    branches:
      - develop
      - staging
    paths:
      - '**/*.vue'
      - '**/*.ts'
      - 'e2e/**/*'
      - yarn.lock
      - .github/workflows/playwright.yml
      - '!__test__/**/*'

jobs:
  test:
    timeout-minutes: 24
    runs-on: ubuntu-latest-32-cores
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Setup .env
        run: cp -r .env.template .env
      - run: yarn
      - run: yarn playwright install --with-deps chromium
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
